name: Push-to-EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: Flutter-Together/calculator_frontend

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "3.38.9.174"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/calculator_frontend"
